### ISSUE TITLE
MSOnline provider doesn't use mandatory resource parameter

### ISSUE THREAD

**Issue by realflash** [mschilli/oauth-cmdline#8]
Currently the MSOnline provider is not providing the 'resource' parameter in its calls. This parameter was optional when I wrote the code, but is now mandatory so all calls are currently failing. Add the parameter.

I will provide a pull request for this.

**Comment by atoomic** [comment]
@realflash I think we can close this issue as $9 is now merged
the next release v0.07 (coming in a few days) will contain this fix
